version: '3'
services:
  portfolio:
    build: .
    image: vuepress-portfolio:latest
    container_name: astro-portfolio
    volumes:
      - .:/app
    ports:
      - 8080:4321
    # command: ["sh", "-c", "npm run docs:dev"]
    command: tail -f /dev/null